title: Hazel's Cat Bed
url: "https://hazel-1212.github.io/"
description: 分享就讀交大電機系的課業、校園生活，做一位引路人。
url: "https://hazel-1212.github.io/"
email: achievegoal9@gmail.com
github_username:  Hazel-1212

theme: minima
plugins:
  - jekyll-feed
